In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np

**Task 1: Array Creation**

In [ ]:
#1. 2 × 2size empty array initializing
import numpy as np

arr1 = np.empty((2,2))
print(arr1)

[[5.68471087e-316 0.00000000e+000]
 [5.68372684e-316 4.88059033e-313]]


In [ ]:
#All 1 array with size 4 × 2 initializing
arr2 = np.ones((4,2))
print(arr2)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
# Return a new array of given shape filled with a value

arr3 = np.full((3,3), 3)
print(arr3)

[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [ ]:
# Return a new array of zeros with same shape as given array

arr4 = np.zeros_like(arr3)
print(arr4)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
# Return a new array of ones with same shape as given array

arr5 = np.ones_like(arr3)
print(arr5)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
#Convert list to NumPy array

new_list = [1,2,3,4]

arr6 = np.array(new_list)
print(arr6)

[1 2 3 4]


Task 2: Array Manipulation (Numerical Ranges and Array indexing)

In [ ]:
#1. Create an array with values ranging from 10 to 49

arr1 = np.arange(10, 50)
print(arr1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# 2. Create a 3X3 matrix with values ranging from 0 to 8
arr2 = np.arange(9).reshape(3,3)
print(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#3. Create a 3X3 identity matrix.
arr3 = np.eye(3)
print(arr3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#4. Create a random array of size 30 and find the mean of the array.
arr4 = np.random.random(30)
mean_value = arr4.mean()

print(arr4)
print("Mean:", mean_value)

[0.47057719 0.99230277 0.42206146 0.54387046 0.60683461 0.55931181
 0.20030785 0.90765153 0.56149423 0.48219541 0.5146648  0.80120813
 0.2770959  0.89673686 0.94429029 0.53397985 0.1033401  0.01688797
 0.53707975 0.04356526 0.586949   0.50616088 0.2059105  0.44379013
 0.75466772 0.25244258 0.57383552 0.38520893 0.77970575 0.53795071]
Mean: 0.5147359312099764


In [ ]:
#5. Create a 10X10 array with random values and find the minimum and maximum values.
arr5 = np.random.random((10,10))

print(arr5)
print("Minimum:", arr5.min())
print("Maximum:", arr5.max())


[[7.06783039e-01 2.39274929e-01 1.09711811e-01 4.81882132e-01
  4.29200591e-02 9.55469716e-01 5.18417548e-01 3.41933712e-01
  2.07070417e-01 2.27905663e-01]
 [4.86320085e-01 8.48731159e-01 2.64473473e-01 8.16242625e-01
  5.57960067e-01 3.53352390e-01 4.14975764e-01 1.09225572e-02
  1.86451812e-01 9.91638534e-01]
 [5.25286667e-03 8.21999392e-01 6.42694020e-01 4.58084185e-01
  1.04958064e-01 8.11473463e-01 2.55938939e-01 8.13161958e-01
  3.91160393e-01 4.21735395e-01]
 [7.85361933e-01 1.08329138e-02 5.02144906e-01 4.99653521e-01
  8.94771204e-01 4.42023302e-01 8.85366733e-01 5.38761967e-01
  9.55928364e-01 6.61070305e-01]
 [6.95992750e-01 7.26455774e-01 4.65120517e-01 5.23417543e-01
  7.45062140e-01 2.99134075e-02 2.70168513e-01 4.57433416e-01
  1.77760354e-01 7.93059430e-01]
 [9.75423777e-01 7.17317372e-01 8.92047206e-02 4.15232615e-01
  5.78656664e-04 3.13700676e-02 4.88383016e-01 9.46087192e-01
  2.26059949e-01 5.37152048e-01]
 [3.52605288e-02 7.15367827e-01 2.20338581e-01 4.40286927e

In [ ]:
#6. Create a zero array of size 10 and replace 5th element with 1.
arr6 = np.zeros(10)

arr6[4] = 1

print(arr6)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#7. Reverse an array arr = [1,2,0,0,4,0].
arr7 = np.array([1,2,0,0,4,0])
reversed_arr = arr7[::-1]

print(reversed_arr)

[0 4 0 0 2 1]


In [ ]:
#8. Create a 2d array with 1 on border and 0 inside.
arr8 = np.ones((5,5))

arr8[1:-1,1:-1] = 0

print(arr8)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#9. Create a 8X8 matrix and fill it with a checkerboard pattern.
arr9 = np.zeros((8,8), dtype=int)

arr9[1::2, ::2] = 1
arr9[::2, 1::2] = 1

print(arr9)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**Task 3: Array Operations**

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

In [ ]:
#1. Add the two array.
add_xy = x + y
print("Addition:\n", add_xy)

Addition:
 [[ 6  8]
 [10 13]]


In [ ]:
#2. Subtract the two array.
sub_xy = x - y
print("Subtraction:\n", sub_xy)

Subtraction:
 [[-4 -4]
 [-4 -3]]


In [ ]:
#3. Multiply the array with any integers of your choice.
mul_x = x * 10
print("Multiply x by 3:\n", mul_x)

Multiply x by 3:
 [[10 20]
 [30 50]]


In [ ]:
#4. Find the square of each element of the array.
square_x = x ** 2
print("Square of x:\n", square_x)

Square of x:
 [[ 1  4]
 [ 9 25]]


In [ ]:
#5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
dot_vw = np.dot(v, w)
print("Dot product v·w:", dot_vw)

dot_xv = np.dot(x, v)
print("Dot product x·v:\n", dot_xv)

dot_xy = np.dot(x, y)
print("Dot product x·y:\n", dot_xy)

Dot product v·w: 219
Dot product x·v:
 [29 77]
Dot product x·y:
 [[19 22]
 [50 58]]


In [ ]:
#6. Concatenate x(and)y along row and Concatenate v(and)w along column. {Hint:try np.concatenate() or np.vstack() functions.
concat_xy = np.concatenate((x,y), axis=0)
print("Row concatenation:\n", concat_xy)

concat_vw = np.concatenate((v,w), axis=0).T
print("Row concatenation:\n", concat_vw)

Row concatenation:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Row concatenation:
 [ 9 10 11 12]


In [ ]:
#7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
v2 = v.reshape(1,2)
result = np.concatenate((x,v2))
print("x and v concatenation:\n", result)

x and v concatenation:
 [[ 1  2]
 [ 3  5]
 [ 9 10]]


**Task 4: Matrix Operations**

In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

In [ ]:
#1. Prove A · A⁻¹ = I
A_inv = np.linalg.inv(A)

identity = np.dot(A, A_inv)

print("A inverse:\n", A_inv)
print("A * A^-1:\n", identity)

A inverse:
 [[-2.    1.  ]
 [ 1.75 -0.75]]
A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [ ]:
#2. Prove AB ≠ BA
AB = np.dot(A,B)
BA = np.dot(B,A)

print("AB:\n", AB)
print("BA:\n", BA)

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]


In [ ]:
#3. Prove (𝐴𝐵)𝑇=𝐵𝑇𝐴𝑇(AB)T=BTAT
left = np.transpose(np.dot(A,B))
right = np.dot(np.transpose(B), np.transpose(A))

print("Left (AB)^T:\n", left)
print("Right B^T A^T:\n", right)

Left (AB)^T:
 [[23 51]
 [13 29]]
Right B^T A^T:
 [[23 51]
 [13 29]]


In [ ]:
#• Solve the following system of Linear equation using Inverse Methods.

#2x − 3y + z = −1
#x − y + 2z = −3
#3x + y − z = 9

A = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3, 1, -1]
])

B = np.array([-1, -3, 9])

# Solve using inverse
A_inv = np.linalg.inv(A)

X = np.dot(A_inv, B)

print("Solution [x, y, z]:")
print(X)

Solution [x, y, z]:
[ 2.  1. -2.]


In [ ]:
import time
size = 1000000
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
result = [list1[i] + list2[i] for i in range(size)]
end = time.time()
print("Python list addition time:", end-start)

#NumPy
arr1 = np.arange(size)
arr2 = np.arange(size)

start = time.time()
result = arr1 + arr2
end = time.time()
print("NumPy addition time:", end-start)

Python list addition time: 0.19310951232910156
NumPy addition time: 0.027304410934448242


In [ ]:
#2. Element-wise Multiplication

start = time.time()
result = [list1[i] * list2[i] for i in range(size)]
end = time.time()
print("Python list multiplication time:", end-start)

#NumPy
start = time.time()
result = arr1 * arr2
end = time.time()
print("NumPy multiplication time:", end-start)

Python list multiplication time: 0.10895752906799316
NumPy multiplication time: 0.014181137084960938


In [ ]:
#3. Dot Product

start = time.time()
dot = sum(list1[i]*list2[i] for i in range(size))
end = time.time()
print("Python dot product time:", end-start)

#NumPy
start = time.time()
dot = np.dot(arr1,arr2)
end = time.time()
print("NumPy dot product time:", end-start)

Python dot product time: 0.11416888236999512
NumPy dot product time: 0.001987934112548828


In [ ]:
#4. Matrix Multiplication

size = 100
A = [[1]*size for i in range(size)]
B = [[1]*size for i in range(size)]

start = time.time()
result = [[sum(A[i][k]*B[k][j] for k in range(size))
          for j in range(size)] for i in range(size)]
end = time.time()
print("Python matrix multiplication time:", end-start)

#NumPy
A = np.ones((1000,1000))
B = np.ones((1000,1000))
start = time.time()
result = np.dot(A,B)
end = time.time()
print("NumPy matrix multiplication time:", end-start)

Python matrix multiplication time: 0.08684420585632324
NumPy matrix multiplication time: 0.05801057815551758


From the observation, it is clear that NumPy performs much faster than Python lists. In every mathematical operation,
NumPy provides quicker results compared to standard Python lists.
This is because NumPy is built on optimized C implementations, supports vectorized operations, and manages memory more efficiently.